import Link from "next/link";
import {ArrowIcon} from "./arrow-icon";
import {SiteHeader} from "./site-header";
import {type Product} from "@/lib/products";
import {type Locale,pathFor,rtl} from "@/lib/i18n";

type Copy={stage:string;lead:string;problemTitle:string;problem:string;caseLabel:string;caseTitle:string;caseIntro:string;steps:[string,string,string];stepNotes:[string,string,string];boundaryTitle:string;boundary:string;reviewTitle:string;review:string;contact:string;back:string;foot:string};
const copy:Record<Locale,Copy>={
  en:{stage:"Research prototype · Phase 0",lead:"A person moving to or living in Morocco may need to make connected decisions about documents, housing and local services. We are testing how a system could show what is known, what is uncertain and what needs confirmation before action.",problemTitle:"One life event crosses many rules.",problem:"A general guide cannot settle an individual case. National rules, personal status, city-level procedures and what happens at a service counter may differ. The research prototype keeps their sources and scope separate, then revisits the decision when circumstances change.",caseLabel:"Synthetic scenario · Not a real user",caseTitle:"A rental payment in Casablanca",caseIntro:"A prospective tenant is asked for six months in advance. The owner's authority, the payee and the current legal treatment of the payment have not been established.",steps:["Record the request","Pause the payment","Identify the checks"],stepNotes:["Keep the landlord's statement and each supporting document distinct; an assertion is not proof.","Do not treat repeated local accounts or a draft translation as clearance for an irreversible transfer.","Check the relevant property record and the recipient's authority with appropriate professionals; unresolved legal questions remain for qualified local review."],boundaryTitle:"What is actually built",boundary:"The repository contains a deterministic case and judgment prototype, controlled synthetic cases and bounded source research. It has no consumer app, live office or booking integration, verified Casablanca residence intake path or completed external legal review. This page is an explanation of research, not a live assistant or a service instruction.",reviewTitle:"Local expertise is the next test.",review:"We welcome scoped review from Moroccan professionals and institutions who can check current procedures, evidence and case-specific limits. Please describe your role, location and the process you can verify; do not send personal documents in the first message.",contact:"Discuss expert review",back:"All systems",foot:"Illustrative research scenario. No personal recommendation or verified live procedure is provided."},
  "zh-CN":{stage:"研发原型 · 第一阶段",lead:"在摩洛哥迁居或生活，一个人常要同时处理证件、住房和本地服务。我们正在验证：系统能否把已知事实、未解决的问题和行动前需要核实的事项清楚分开，并在现实情况变化时更新判断。",problemTitle:"一件生活事务，牵动多条规则。",problem:"通用攻略不能代替个人判断。全国规定、个人身份、城市办理流程和现场实际做法可能不一致。研究原型尝试保留各自来源与适用范围，遇到新情况再重新判断。",caseLabel:"模拟案例 · 并非真实用户",caseTitle:"卡萨布兰卡的一笔租房付款",caseIntro:"拟租客被要求预付六个月款项；房东权属、收款人权限和这笔款项的现行法律性质尚未核实。",steps:["记录主张","暂停付款","明确核查"],stepNotes:["分别保存对方说法和支持文件；有人提出要求，不等于要求已被证明合理。","本地经验反复出现，或有一份待审翻译，都不能直接解除不可逆付款风险。","核对相关房产记录和收款权限；未解决的法律问题交由合资格的当地专业人士审查。"],boundaryTitle:"目前实际完成了什么",boundary:"仓库已有确定性的案例判断原型、受控模拟案例和限定范围的来源研究；尚无面向消费者的应用、实时办事接口、已核实的卡萨布兰卡居留受理路径或完成的外部法律专家审查。本页介绍研发工作，不提供实时办理指引。",reviewTitle:"下一步需要当地专家核对。",review:"欢迎熟悉摩洛哥现行流程的专业人士或机构，就具体城市、身份和办理事项核查资料与实际步骤。首次联系请说明身份、地区和可核对的流程，无需发送个人证件。",contact:"讨论专业核对",back:"全部系统",foot:"本页案例为模拟研究示例，不构成针对个人的建议或已核实的实时办理流程。"},
  "zh-TW":{stage:"研發原型 · 第一階段",lead:"在摩洛哥遷居或生活，往往要同時處理證件、住房及本地服務。我們正驗證系統能否區分已知事實、未解問題和行動前須核實的事項，並在情況改變時更新判斷。",problemTitle:"一件生活事務，牽動多項規則。",problem:"通用攻略無法取代個別判斷。全國規定、個人身分、城市流程與現場做法可能不同。研究原型保留各自來源和適用範圍，並隨新情況重新判斷。",caseLabel:"模擬案例 · 非真實用戶",caseTitle:"卡薩布蘭卡的一筆租屋付款",caseIntro:"準租客被要求預付六個月款項；房東權屬、收款人權限及款項的現行法律性質均未核實。",steps:["記錄主張","暫停付款","明確核查"],stepNotes:["分別保存對方說法及支持文件；提出要求不等於要求已獲證實。","重複的本地經驗或待審譯文，不能直接解除不可逆付款風險。","核對房產紀錄和收款權限；法律疑問交由合資格的當地專業人士審查。"],boundaryTitle:"目前實際完成了甚麼",boundary:"已有案例判斷原型、受控模擬案例與有限的來源研究；尚無消費者應用、即時辦事接口、已核實的卡薩布蘭卡居留受理路徑或完成的外部法律審查。本頁介紹研發工作，不提供即時辦理指引。",reviewTitle:"下一步需要當地專家核對。",review:"歡迎熟悉摩洛哥現行流程的專業人士或機構，核查特定城市、身分及事項的資料與實際步驟。首次聯絡請說明角色和範圍，毋須提供個人證件。",contact:"討論專業核對",back:"全部系統",foot:"模擬研究案例，不構成個人建議或已核實的即時辦事流程。"},
  fr:{stage:"Prototype de recherche · Phase 0",lead:"S'installer ou vivre au Maroc implique souvent plusieurs décisions liées : documents, logement et services locaux. Nous étudions comment distinguer les faits établis, les inconnues et les vérifications nécessaires avant d'agir.",problemTitle:"Une démarche, plusieurs réalités.",problem:"Une fiche générale ne suffit pas pour un cas individuel. Règles nationales, situation personnelle, procédures locales et pratique au guichet peuvent diverger. Le prototype sépare leurs sources et réévalue la décision quand le contexte change.",caseLabel:"Cas fictif · Aucun utilisateur réel",caseTitle:"Un paiement locatif à Casablanca",caseIntro:"On demande à un locataire potentiel six mois d'avance. Le titre du bailleur, le destinataire du paiement et la qualification juridique actuelle de la somme restent à vérifier.",steps:["Consigner la demande","Suspendre le paiement","Cibler les contrôles"],stepNotes:["Conserver séparément les déclarations et les documents : une demande n'est pas une preuve.","Des récits locaux répétés ou une traduction non validée ne lèvent pas le risque d'un virement irréversible.","Vérifier les données foncières et le pouvoir du bénéficiaire ; soumettre les questions juridiques à un professionnel local qualifié."],boundaryTitle:"Ce qui existe aujourd'hui",boundary:"Le dépôt contient un prototype déterministe de cas et de jugement, des scénarios fictifs contrôlés et une recherche documentaire limitée. Il n'existe ni application grand public, ni connexion aux guichets, ni parcours de séjour casablancais vérifié, ni revue juridique externe achevée. Cette page présente une recherche, pas un service opérationnel.",reviewTitle:"La prochaine étape : l'examen local.",review:"Nous invitons les professionnels et institutions au Maroc à vérifier des procédures actuelles, leurs sources et leur portée. Indiquez votre rôle, votre ville et le processus que vous pouvez examiner, sans envoyer de pièces personnelles au premier contact.",contact:"Discuter d'une revue experte",back:"Tous les systèmes",foot:"Scénario de recherche fictif ; aucune recommandation individuelle ou procédure en temps réel validée."},
  ar:{stage:"نموذج بحثي · المرحلة الأولى",lead:"تتداخل قرارات الوثائق والسكن والخدمات عند الانتقال إلى المغرب أو العيش فيه. نختبر طريقة لتمييز ما ثبت وما بقي مجهولاً وما يجب التحقق منه قبل اتخاذ خطوة.",problemTitle:"حاجة واحدة، قواعد متعددة.",problem:"لا تحسم الإرشادات العامة حالة الفرد. قد تختلف القواعد الوطنية والصفة الشخصية والإجراءات المحلية والممارسة في المكاتب. يفصل النموذج مصادرها ونطاقها ويعيد النظر عند تغير الظروف.",caseLabel:"حالة افتراضية · ليست لمستخدم حقيقي",caseTitle:"دفعة إيجار في الدار البيضاء",caseIntro:"طُلب من مستأجر محتمل دفع ستة أشهر مقدماً. ملكية المؤجر وصلاحية متلقي المال والوصف القانوني الحالي للمبلغ أمور غير مثبتة.",steps:["تسجيل الطلب","تعليق الدفع","تحديد التحقق"],stepNotes:["فصل أقوال الأطراف عن المستندات؛ الطلب ليس دليلاً كافياً.","التجارب المتكررة أو ترجمة غير معتمدة لا تجيز تحويلاً لا يمكن التراجع عنه.","فحص السجل العقاري وصلاحية المتلقي، وعرض المسائل القانونية على مختص محلي مؤهل."],boundaryTitle:"ما الذي بُني فعلاً",boundary:"يوجد نموذج تجريبي للحالات والأحكام واختبارات افتراضية وبحث محدود في المصادر. لا يوجد تطبيق للمستهلك أو ربط مباشر بالإدارات أو مسار إقامة مؤكد بالدار البيضاء أو مراجعة قانونية خارجية مكتملة. هذه صفحة بحث وليست خدمة إجراءات مباشرة.",reviewTitle:"نحتاج مراجعة الخبراء المحليين.",review:"نرحب بمراجعة المهنيين والمؤسسات المغربية للإجراءات الحالية ونطاقها. يرجى توضيح الدور والمدينة والإجراء الممكن مراجعته، دون إرسال وثائق شخصية في أول رسالة.",contact:"ناقش مراجعة الخبراء",back:"جميع الأنظمة",foot:"حالة بحثية افتراضية؛ لا توصية شخصية أو إجراء آني معتمد."},
  ary:{stage:"نموذج بحثي · المرحلة اللولة",lead:"العيش أو الانتقال للمغرب كيجمع قرارات على الوثائق والسكن والخدمات. كنجرّبو كيفاش نفرقو بين المعلوم، والمجهول، وداكشي اللي خاصو تأكيد قبل أي خطوة.",problemTitle:"قضية وحدة، ومساطر متعددة.",problem:"الدليل العام ما كيحسمش حالة شخص بعينو. القانون والوضعية الشخصية والمساطر المحلية والواقع فالإدارة يقدرو يختلفو. النموذج كيبقي المصادر والحدود ديالها واضحين.",caseLabel:"حالة مفترضة · ماشي مستخدم حقيقي",caseTitle:"دفعة كراء فالدار البيضاء",caseIntro:"تطلب من مكتري محتمل يخلص ستة شهور مسبقاً. الملكية وصلاحية اللي غادي يتوصل بالفلوس والوضع القانوني الحالي مازال ما تأكدوش.",steps:["سجل الطلب","وقف الدفع","حدد التحقق"],stepNotes:["خلي كلام الطرف والوثائق منفصلين؛ الطلب بوحدو ماشي دليل.","تجارب الناس أو ترجمة ما تراجعاتش ما كتكفيش باش يتحول مبلغ يصعب يرجع.","تحقق من السجل العقاري وصلاحية المستفيد وخلي الأسئلة القانونية لمختص محلي مؤهل."],boundaryTitle:"شنو مبني دابا",boundary:"كاين نموذج بحثي للحالات والأحكام واختبارات مفترضة وبحث محدود فالمصادر. ما كاين لا تطبيق للمستخدمين لا ربط مباشر بالإدارات لا مسار إقامة مؤكد فالدار البيضاء لا مراجعة قانونية خارجية مكتملة.",reviewTitle:"خاصنا مراجعة محلية.",review:"مرحبا بالمهنيين والمؤسسات اللي يقدرو يراجعو المساطر الحالية. بين الدور والمدينة والإجراء، وبلا وثائق شخصية فأول تواصل.",contact:"ناقش المراجعة",back:"جميع الأنظمة",foot:"مثال بحثي مفترض؛ ماشي نصيحة شخصية ولا مسطرة مباشرة مؤكدة."},
  es:{stage:"Prototipo de investigación · Fase 0",lead:"Vivir o mudarse a Marruecos conecta decisiones sobre documentos, vivienda y servicios. Estudiamos cómo distinguir hechos, incógnitas y verificaciones antes de actuar.",problemTitle:"Una situación, varias reglas.",problem:"Una guía general no resuelve un caso particular. La norma, la situación personal, el trámite local y la práctica pueden diferir. El prototipo separa las fuentes y reevalúa la decisión cuando cambian los hechos.",caseLabel:"Caso simulado · No es un usuario real",caseTitle:"Un pago de alquiler en Casablanca",caseIntro:"Se piden seis meses por adelantado. Aún no se han verificado la titularidad, la facultad del receptor ni el tratamiento legal vigente del pago.",steps:["Registrar la petición","Pausar el pago","Definir las comprobaciones"],stepNotes:["Separar afirmaciones y documentos: una petición no es una prueba.","Relatos locales o traducciones sin revisar no autorizan una transferencia irreversible.","Comprobar el registro y la autoridad del receptor; remitir las dudas legales a un profesional local cualificado."],boundaryTitle:"Estado real del proyecto",boundary:"Hay un prototipo de casos, pruebas simuladas e investigación documental limitada. No hay aplicación pública, conexión con oficinas, ruta de residencia en Casablanca verificada ni revisión legal externa completa. Esta página no ofrece instrucciones operativas.",reviewTitle:"Buscamos revisión local.",review:"Invitamos a profesionales e instituciones en Marruecos a verificar procedimientos y límites concretos. Indique su función, ciudad y trámite; no envíe documentos personales en el primer contacto.",contact:"Hablar sobre revisión",back:"Todos los sistemas",foot:"Ejemplo simulado; no es una recomendación individual ni un trámite vigente verificado."},
  ja:{stage:"研究試作 · 第0段階",lead:"モロッコでの移住や生活には、書類、住居、地域サービスに関する複数の判断が伴います。分かっていること、不明なこと、行動前に確認すべきことを区別する方法を検証しています。",problemTitle:"一つの生活課題に複数の条件。",problem:"一般的な案内だけでは個別の事案は決まりません。国の規則、本人の状況、都市の手続き、窓口の運用を分けて扱い、状況の変化に応じて判断を見直します。",caseLabel:"架空の事例 · 実際の利用者ではありません",caseTitle:"カサブランカでの賃料支払い",caseIntro:"6か月分の前払いを求められていますが、所有権、受取人の権限、支払いの法的性質は未確認です。",steps:["主張を記録","支払いを保留","確認項目を特定"],stepNotes:["当事者の発言と資料を区別します。要求は証拠ではありません。","地域の体験談や未審査の翻訳だけで、取り消しにくい送金を認めません。","登記と受取権限を確認し、法律上の疑問は現地の有資格者に委ねます。"],boundaryTitle:"現在の開発状況",boundary:"ケース判断の試作、模擬事例、限定的な資料調査があります。一般向けアプリ、窓口との接続、確認済みのカサブランカ居留手続き、完了した外部法律審査はありません。",reviewTitle:"現地専門家による検証を募集しています。",review:"現行手続きと適用範囲を確認できる方は、役割、都市、確認可能な手続きをお知らせください。初回連絡で個人書類は不要です。",contact:"専門家による検証を相談",back:"すべてのシステム",foot:"架空の研究事例であり、個別の助言や確認済みの現行手続きを示すものではありません。"},
  th:{stage:"ต้นแบบวิจัย · ระยะที่ 0",lead:"การย้ายไปหรือใช้ชีวิตในโมร็อกโกเกี่ยวข้องกับการตัดสินใจเรื่องเอกสาร ที่อยู่อาศัย และบริการท้องถิ่น เรากำลังทดสอบวิธีแยกข้อเท็จจริง สิ่งที่ยังไม่รู้ และเรื่องที่ต้องตรวจสอบก่อนลงมือ",problemTitle:"เรื่องเดียวเกี่ยวข้องกับหลายกฎ",problem:"คู่มือทั่วไปไม่สามารถตัดสินกรณีของแต่ละคนได้ กฎระดับชาติ สถานะส่วนบุคคล ขั้นตอนของเมือง และการปฏิบัติจริงอาจต่างกัน ต้นแบบจึงแยกแหล่งข้อมูลและขอบเขตการใช้",caseLabel:"กรณีจำลอง · ไม่ใช่ผู้ใช้จริง",caseTitle:"การจ่ายค่าเช่าในคาซาบลังกา",caseIntro:"ผู้เช่าถูกขอให้จ่ายล่วงหน้าหกเดือน แต่ยังไม่ได้ยืนยันกรรมสิทธิ์ อำนาจของผู้รับเงิน หรือสถานะทางกฎหมายปัจจุบันของเงินก้อนนี้",steps:["บันทึกคำขอ","ระงับการจ่าย","กำหนดสิ่งที่ต้องตรวจ"],stepNotes:["แยกคำกล่าวอ้างออกจากเอกสาร คำขอเพียงอย่างเดียวไม่ใช่หลักฐาน","ประสบการณ์ที่เล่าซ้ำหรือคำแปลที่ยังไม่ตรวจสอบไม่เพียงพอสำหรับการโอนเงินที่ย้อนกลับยาก","ตรวจทะเบียนทรัพย์สินและอำนาจรับเงิน แล้วให้ผู้เชี่ยวชาญท้องถิ่นตรวจคำถามทางกฎหมาย"],boundaryTitle:"สิ่งที่สร้างแล้วจริง",boundary:"มีต้นแบบการพิจารณากรณีทดสอบจำลองและการวิจัยแหล่งข้อมูลที่จำกัด ยังไม่มีแอปสำหรับผู้ใช้ การเชื่อมต่อหน่วยงาน เส้นทางรับคำขอพำนักในคาซาบลังกาที่ตรวจยืนยัน หรือการทบทวนกฎหมายภายนอกที่เสร็จสิ้น",reviewTitle:"ต้องการการตรวจสอบจากผู้เชี่ยวชาญในพื้นที่",review:"เชิญผู้เชี่ยวชาญหรือหน่วยงานในโมร็อกโกตรวจขั้นตอนจริง โปรดระบุบทบาท เมือง และขั้นตอนที่ตรวจได้ โดยไม่ต้องส่งเอกสารส่วนตัวในการติดต่อครั้งแรก",contact:"พูดคุยเรื่องการตรวจสอบ",back:"ระบบทั้งหมด",foot:"กรณีวิจัยจำลอง ไม่ใช่คำแนะนำเฉพาะบุคคลหรือขั้นตอนปัจจุบันที่ยืนยันแล้ว"}
};

export function MoroccoLifeView({locale,product}:{locale:Locale;product:Product}){
  const m=copy[locale],direction=rtl(locale)?"rtl":"ltr";
  return <><SiteHeader locale={locale}/><main className="shell detail morocco-page" dir={direction}>
    <Link className="back-link" href={pathFor(locale,"/systems")}><ArrowIcon direction="left"/> {m.back}</Link>
    <div className="detail-intro"><div><p className="overline">{product.number} / {product.domain}</p><h1>{product.title}<span className="detail-dot">.</span></h1></div><span className="status">{m.stage}</span></div>
    <p className="detail-lead">{m.lead}</p>
    <section className="morocco-problem"><p className="overline">MatterTurn Ai / Morocco</p><h2>{m.problemTitle}</h2><p>{m.problem}</p></section>
    <section className="morocco-case"><div className="morocco-case-heading"><span className="small-label">{m.caseLabel}</span><h2>{m.caseTitle}</h2><p>{m.caseIntro}</p></div><ol>{m.steps.map((step,i)=><li key={step}><span>0{i+1}</span><div><h3>{step}</h3><p>{m.stepNotes[i]}</p></div></li>)}</ol></section>
    <section className="morocco-boundary"><h2>{m.boundaryTitle}</h2><p>{m.boundary}</p></section>
    <section className="detail-cta"><div><span className="small-label">{m.reviewTitle}</span><p>{m.review}</p></div><Link className="button-dark" href={pathFor(locale,"/contact")}>{m.contact} <ArrowIcon/></Link></section>
  </main><footer className="footer shell" dir={direction}><span>© MatterTurn Ai</span><span>{m.foot}</span><Link href={pathFor(locale,"/systems")}>{m.back} <ArrowIcon direction="up"/></Link></footer></>;
}
