export type Product = { slug: string; number: string; title: string; domain: string; status: string; summary: string; question: string; signals: string[]; work: string[]; outcome: string };
export const products: Product[] = [
  {slug:"real-estate",number:"01",title:"Real Estate",domain:"Investment & development",status:"Internal validation",summary:"Examine an investment opportunity through evidence, assumptions, risk and expert challenge.",question:"Should we pursue this property, and what would change the decision?",signals:["Asset documents","Market evidence","Financial assumptions","Local constraints"],work:["Define the decision and jurisdiction","Trace material claims to evidence","Stress-test conflicts and assumptions","Prepare questions for expert review"],outcome:"A reviewable investment case with explicit limits. A client-grade report requires a verified case and human sign-off."},
  {slug:"international-brand",number:"02",title:"International Brand Strategy & Marketing",domain:"Brand strategy & market growth",status:"In development",summary:"Connect local consumer voices, market evidence, brand positioning and marketing execution across countries.",question:"Which market should this product enter, how should it be positioned, and how should the plan reach customers?",signals:["Product context","Local consumer voices","Competition","Culture & channels"],work:["Understand the product and audience","Compare candidate markets","Separate observation from insight","Develop strategy and marketing options"],outcome:"A reviewable market, brand and marketing direction with evidence gaps and assumptions visible."},
  {slug:"banking-frontline",number:"03",title:"Banking Frontline Service",domain:"Customer service decisions",status:"In development",summary:"Help bank service teams handle customer questions with traceable service information and clear escalation points.",question:"What can we confirm for this customer, and what needs specialist review?",signals:["Customer question","Service conditions","Bank guidance","Information gaps"],work:["Clarify the request and applicable bank","Check relevant service information","Identify gaps and escalation needs"],outcome:"A reviewable service response path. It is not connected to bank accounts or transaction systems."},
  {slug:"travel",number:"04",title:"Professional Services for Tourists & Travel Agencies",domain:"Traveler support & agency operations",status:"In development",summary:"Help travelers find and compare flights, tickets and itineraries, while helping travel agencies reduce information gathering, purchasing and operating effort.",question:"Which travel options fit my needs, and what will they cost in time and money?",signals:["Trip needs","Flight and ticket options","Itinerary constraints","Price and availability"],work:["Clarify traveler needs","Compare available options and total costs","Organize booking and itinerary steps"],outcome:"A clear plan for comparing and arranging travel services; live prices and availability require connected sources."},
  {slug:"cross-border",number:"05",title:"Cross-border Goods Trade Services",domain:"Sourcing & trade",status:"Synthetic testing",summary:"Assess products and suppliers across Chinese platforms and destination markets.",question:"Is this sourcing opportunity commercially and operationally sound?",signals:["Platform evidence","Supplier claims","Delivery economics","Destination requirements"],work:["Compare the offer and evidence","Surface unknowns and platform limits","Assess commercial and operational risks"],outcome:"A qualified sourcing judgment, pending live-platform validation."},
  {slug:"morocco-life",number:"06",title:"Morocco Life Personal Assistant",domain:"Everyday life in Morocco",status:"In development",summary:"Help residents and visitors get oriented around documents, housing, transport and everyday local services.",question:"Given my circumstances, what do I need to know or arrange next in Morocco?",signals:["Personal circumstances","Location","Official requirements","Local service information"],work:["Understand the situation","Find relevant local information","Organize practical steps and confirmation points"],outcome:"A practical next-step guide with uncertainties and official confirmation points visible."},
  {slug:"financial-markets",number:"07",title:"Financial Securities Decision System",domain:"Securities analysis",status:"In development",summary:"Support decisions on financial securities with time-bound market evidence, instrument terms and competing explanations.",question:"What has changed for this security, and does it change the investment judgment?",signals:["Security terms","Market data","Events and timing","Competing explanations"],work:["Bind evidence to the security and decision time","Test competing interpretations","Revise conclusions affected by new facts"],outcome:"A traceable securities judgment with remaining uncertainty and assumptions shown."},
  {slug:"sales-opportunity",number:"08",title:"Sales Opportunity Judgment",domain:"B2B sales research",status:"Exploration",summary:"Research whether a real B2B sales opportunity is worth pursuing, with an explicit boundary against any live outreach or CRM action.",question:"Does this prospect's public evidence actually indicate a commercial problem worth pursuing?",signals:["Prospect public signals","Research budget","Evidence of need and authority","Prior research ledger"],work:["Research public signals against the prospect","Qualify against evidence of need, budget, authority","Track every research action in an auditable ledger"],outcome:"A qualification outcome bound to evidence — including a valid zero-opportunity result. No outreach, CRM write, or commercial offer exists."},
  {slug:"medical-business",number:"09",title:"Medical Business Decision System",domain:"Healthcare business",status:"Design stage",summary:"Designing a bounded system for commercial decisions in healthcare contexts.",question:"Which commercial choice is justified by the available evidence?",signals:["Business context","Regulatory setting","Stakeholder evidence"],work:["Define the use case and boundaries","Identify reliable sources and qualified reviewers"],outcome:"A design direction, not a clinical or medical decision tool."},
];
export const productBySlug = (slug: string) => products.find(p=>p.slug===slug);
