import {products,type Product} from "./products";
import {type Locale} from "./i18n";

type Compact = [string,string,string,string,string,string,string];
const status:Record<Locale,Record<string,string>> = {
 en:{"Internal validation":"Internal validation","In development":"In development","Prototype tested":"Prototype tested","Synthetic testing":"Synthetic testing","Exploration":"Exploration","Design stage":"Design stage"},
 "zh-CN":{"Internal validation":"内部验证","In development":"研发中","Prototype tested":"原型已测试","Synthetic testing":"模拟案例测试","Exploration":"探索中","Design stage":"方案设计"},
 "zh-TW":{"Internal validation":"內部驗證","In development":"研發中","Prototype tested":"原型已測試","Synthetic testing":"模擬案例測試","Exploration":"探索中","Design stage":"方案設計"},
 fr:{"Internal validation":"Validation interne","In development":"En développement","Prototype tested":"Prototype testé","Synthetic testing":"Tests sur cas fictifs","Exploration":"Exploration","Design stage":"Conception"},
 ar:{"Internal validation":"تحقق داخلي","In development":"قيد التطوير","Prototype tested":"نموذج أولي مختبر","Synthetic testing":"اختبار ببيانات اصطناعية","Exploration":"مرحلة الاستكشاف","Design stage":"مرحلة التصميم"},
 ary:{"Internal validation":"تجربة داخلية","In development":"باقي كيتطور","Prototype tested":"تجرّب النموذج الأولي","Synthetic testing":"تجربة بمعطيات مفترضة","Exploration":"فمرحلة الاستكشاف","Design stage":"فمرحلة التصميم"},
 es:{"Internal validation":"Validación interna","In development":"En desarrollo","Prototype tested":"Prototipo probado","Synthetic testing":"Pruebas con casos ficticios","Exploration":"Exploración","Design stage":"Diseño"},
 ja:{"Internal validation":"内部検証中","In development":"開発中","Prototype tested":"試作品をテスト済み","Synthetic testing":"模擬データで検証中","Exploration":"検討中","Design stage":"設計段階"},
 th:{"Internal validation":"ตรวจสอบภายใน","In development":"กำลังพัฒนา","Prototype tested":"ทดสอบต้นแบบแล้ว","Synthetic testing":"ทดสอบด้วยกรณีจำลอง","Exploration":"ระยะสำรวจ","Design stage":"ระยะออกแบบ"}
};
const localized:Record<Exclude<Locale,"en">,Record<string,Compact>> = {
 "zh-CN":{
  "banking-frontline":["银行专业前端服务","客户服务判断","帮助银行前端人员依据可追溯的服务信息回应客户问题，并识别转交专业人员的时点。","对这位客户，目前能确认什么？哪些需要专业复核？","形成可复核的服务回应路径；目前未连接银行账户或交易系统。","客户问题|服务条件|银行指引|信息缺口","澄清需求与适用银行|核对相关服务信息|识别缺口与转交需要"],
  "real-estate":["房地产","投资与开发","以证据、假设、风险和专家质询审视投资机会。","这个房地产项目值得推进吗？什么事实会改变判断？","可审查的投资分析及其限制。客户级报告还需要真实案例验证和专家签署。","资产文件|市场证据|财务假设|当地限制","明确决策与适用地区|追溯关键主张的证据|检验冲突和假设|准备专家审查问题"],
  "international-brand":["国际品牌战略与市场营销系统", "品牌战略与市场营销", "把当地消费者声音、市场证据、品牌定位与市场营销执行连接起来。", "产品应该进入哪里？如何面向当地消费者定位？", "一份清楚标明证据缺口与假设的市场及定位建议。", "产品理解|当地消费者声音|竞争与文化|营销渠道", "理解产品与受众|比较目标市场|区分观察与洞察|形成品牌与营销方案"],
  travel:["游客与旅行社专业服务系统", "游客服务与旅行社运营", "帮助游客比较机票、门票和行程，降低信息获取与选择成本；帮助旅行社整理采购信息与运营流程。", "哪些旅行选项适合我的需求？时间与费用如何？", "清晰的旅行选项和安排路径；实时价格与余量需要接入可靠数据源。", "旅行需求|机票与门票|行程安排|价格与余量", "明确游客需求|比较选项与综合成本|整理采购和行程步骤"],
  "cross-border":["跨境商品贸易服务系统","采购与贸易","评估中国平台上的商品与供应商及目的地市场条件。","这次采购机会在商业和执行上是否可行？","附带条件的采购判断，尚待真实平台数据验证。","平台证据|供应商主张|交付成本|目的地要求","比较报价与证据|指出未知及平台限制|评估商业与执行风险"],
  "morocco-life":["摩洛哥生活私人助理", "摩洛哥日常生活", "帮助居民和访客了解证件、住房、交通和日常本地服务。", "根据我在摩洛哥的具体情况，下一步该怎么做？", "结合个人情况的行动路径，标明不确定性及官方核实点。", "个人情况|所在地点|官方要求|本地服务信息", "了解具体情况|查找相关信息|整理办理步骤与确认事项"],
  "financial-markets":["金融证券决策系统", "证券分析", "结合证券条款、市场证据与不同解释，支持可追溯的金融证券判断。", "发生了什么变化？它是否改变当前市场判断？", "可追溯的市场判断及尚存的不确定性。", "证券条款|市场数据|事件与时间|不同解释", "把证据对应到证券与判断时点|检验不同解释|更新受新事实影响的结论"],
  "medical-business":["医疗商业决策系统","医疗健康商业","为医疗健康领域的商业判断设计明确边界的系统。","现有证据支持哪种商业选择？","仍处设计阶段，不用于临床或医疗判断。","商业背景|监管环境|相关方证据","界定用途和边界|识别可靠来源与合适的审查专家"]
 },
 "zh-TW":{
  "banking-frontline":["銀行專業前端服務","客戶服務判斷","協助銀行前端人員根據可追溯的服務資訊回應客戶問題，並識別轉交專業人員的時點。","對這位客戶，目前能確認甚麼？哪些需要專業覆核？","形成可覆核的服務回應路徑；目前未連接銀行帳戶或交易系統。","客戶問題|服務條件|銀行指引|資訊缺口","釐清需求與適用銀行|核對相關服務資訊|識別缺口與轉交需要"],
  "real-estate":["房地產","投資與開發","以證據、假設、風險和專家質詢審視投資機會。","這個房地產項目值得推進嗎？甚麼事實會改變判斷？","可供審查的投資分析及其限制。客戶級報告仍需真實案例驗證和專家簽署。","資產文件|市場證據|財務假設|當地限制","明確決策與適用地區|追溯關鍵主張的證據|檢驗衝突與假設|準備專家審查問題"],
  "international-brand":["國際品牌戰略與市場營銷系統", "品牌戰略與市場營銷", "連結當地消費者聲音、市場證據、品牌定位與市場營銷執行。", "產品應進入哪個市場？如何面向當地消費者定位？", "清楚標示證據缺口與假設的市場及定位建議。", "產品理解|當地消費者聲音|競爭與文化|營銷渠道", "理解產品與受眾|比較目標市場|區分觀察與洞察|形成品牌與營銷方案"],
  travel:["遊客與旅行社專業服務系統", "旅客服務與旅行社營運", "協助旅客比較機票、門票與行程，降低取得資訊及選擇的成本；協助旅行社整理採購資訊與營運流程。", "哪些旅行選項符合我的需要？時間與費用如何？", "清晰的旅行選項與安排路徑；即時價格與名額需接入可靠資料來源。", "旅行需求|機票與門票|行程安排|價格與名額", "釐清旅客需要|比較選項與綜合成本|整理採購與行程步驟"],
  "cross-border":["跨境商品貿易服務系統","採購與貿易","評估中國平台的商品與供應商，以及目的地市場條件。","這次採購機會在商業和執行上可行嗎？","附有條件的採購判斷，仍待真實平台資料驗證。","平台證據|供應商主張|交付成本|目的地要求","比較報價與證據|指出未知及平台限制|評估商業與執行風險"],
  "morocco-life":["摩洛哥生活私人助理", "摩洛哥日常生活", "協助居民及訪客了解證件、住房、交通與日常本地服務。", "按我在摩洛哥的具體情況，下一步應如何做？", "結合個人情況的行動路徑，標明不確定性與官方核實點。", "個人情況|所在地點|官方要求|本地服務資訊", "了解具體情況|查找相關資訊|整理辦理步驟與確認事項"],
  "financial-markets":["金融證券決策系統", "證券分析", "結合證券條款、市場證據與不同解釋，支持可追溯的金融證券判斷。", "發生了甚麼變化？是否改變當前市場判斷？", "可追溯的市場判斷及尚存的不確定性。", "證券條款|市場數據|事件與時間|不同解釋", "把證據對應到證券與判斷時點|檢驗不同解釋|更新受新事實影響的結論"],
  "medical-business":["醫療商業決策系統","醫療健康商業","為醫療健康領域的商業判斷設計明確邊界的系統。","現有證據支持哪種商業選擇？","仍處設計階段，不用於臨床或醫療判斷。","商業背景|監管環境|相關方證據","界定用途與邊界|識別可靠來源與適合的審查專家"]
 },
 fr:{
  "banking-frontline":["Service bancaire de première ligne","Décisions de service client","Aider les équipes en agence à traiter les demandes avec des informations traçables et des points de transfert clairs.","Que pouvons-nous confirmer pour ce client et que faut-il faire vérifier par un spécialiste ?","Un parcours de réponse vérifiable ; aucune connexion aux comptes ou aux systèmes de transaction.","Demande du client|Conditions de service|Consignes bancaires|Informations manquantes","Préciser la demande et la banque concernée|Vérifier les informations de service|Repérer les manques et les transferts nécessaires"],
  "real-estate":["Immobilier","Investissement et développement","Évaluer une opportunité par les preuves, les hypothèses, les risques et la contradiction experte.","Faut-il poursuivre ce projet immobilier ? Quels faits changeraient la décision ?","Un dossier d’investissement examinable avec ses limites. Un rapport client exige encore un cas vérifié et une validation humaine.","Documents de l’actif|Données du marché|Hypothèses financières|Contraintes locales","Définir la décision et la juridiction|Relier les affirmations aux preuves|Tester les contradictions et hypothèses|Préparer la revue experte"],
  "international-brand":["Stratégie de marque internationale et marketing", "Stratégie de marque et marketing", "Relier les voix des consommateurs locaux, les données du marché, le positionnement et la mise en œuvre marketing.", "Où entrer et comment positionner ce produit auprès des consommateurs locaux ?", "Une recommandation de marché et de positionnement qui expose les lacunes et hypothèses.", "Produit et public|Consommateurs locaux|Concurrence et culture|Canaux marketing", "Comprendre le produit et le public|Comparer les marchés|Distinguer observation et insight|Définir marque et marketing"],
  travel:["Services professionnels pour touristes et agences de voyage", "Voyageurs et agences", "Aider les voyageurs à comparer vols, billets et itinéraires, et les agences à réduire le travail de recherche, d’achat et de gestion.", "Quelles options correspondent à mes besoins, pour quel coût et quel délai ?", "Des options et un parcours de réservation clairs ; les prix et disponibilités en temps réel exigent des sources connectées.", "Besoins du voyageur|Vols et billets|Itinéraire|Prix et disponibilités", "Préciser les besoins|Comparer les options et coûts complets|Organiser achats et itinéraire"],
  "cross-border":["Services de commerce transfrontalier de produits","Sourcing et commerce","Évaluer produits et fournisseurs sur les plateformes chinoises et sur les marchés de destination.","Cette opportunité d’approvisionnement est-elle viable ?","Un jugement conditionnel, sous réserve de validation sur des plateformes réelles.","Données de plateformes|Affirmations des fournisseurs|Coûts de livraison|Exigences du marché cible","Comparer offres et preuves|Exposer les inconnues et limites|Évaluer les risques commerciaux"],
  "morocco-life":["Assistant personnel de vie au Maroc", "Vie quotidienne au Maroc", "Aider résidents et visiteurs à trouver des informations sur les démarches, le logement, les transports et les services du quotidien.", "Quelle est la prochaine étape adaptée à ma situation au Maroc ?", "Un parcours contextualisé indiquant les incertitudes et vérifications officielles.", "Situation personnelle|Lieu|Exigences officielles|Services locaux", "Comprendre la situation|Trouver les informations utiles|Organiser les étapes et vérifications"],
  "financial-markets":["Système de décision sur les titres financiers", "Analyse de titres", "Appuyer les décisions sur les titres financiers grâce aux conditions des instruments, aux données datées et à des interprétations concurrentes.", "Qu’est-ce qui a changé et cela modifie-t-il l’analyse actuelle ?", "Une analyse traçable avec les incertitudes restantes.", "Conditions du titre|Données du marché|Événements datés|Interprétations concurrentes", "Relier preuves, titre et date de décision|Tester les interprétations|Réviser les conclusions touchées"],
  "medical-business":["Système de décision commerciale en santé","Activité de santé","Concevoir un système délimité pour les décisions commerciales dans le secteur de la santé.","Quel choix commercial les preuves disponibles justifient-elles ?","Un projet en conception, sans usage de décision clinique ou médicale.","Contexte commercial|Cadre réglementaire|Données des parties prenantes","Définir l’usage et ses limites|Identifier les sources et experts qualifiés"]
 },
 ar:{
  "banking-frontline":["الخدمة المصرفية الأمامية","قرارات خدمة العملاء","مساعدة موظفي الواجهة على معالجة أسئلة العملاء استناداً إلى معلومات خدمة قابلة للتتبع ونقاط إحالة واضحة.","ما الذي يمكن تأكيده لهذا العميل، وما الذي يحتاج إلى مراجعة مختص؟","مسار رد قابل للمراجعة؛ لا يوجد اتصال بالحسابات أو أنظمة المعاملات المصرفية.","سؤال العميل|شروط الخدمة|إرشادات البنك|نقص المعلومات","توضيح الطلب والبنك المعني|التحقق من معلومات الخدمة|تحديد النواقص والحاجة إلى الإحالة"],
  "real-estate":["العقارات","الاستثمار والتطوير","دراسة فرص الاستثمار وفق الأدلة والافتراضات والمخاطر ومراجعة الخبراء.","هل ينبغي متابعة هذا العقار؟ وما الحقائق التي قد تغير القرار؟","ملف استثماري قابل للمراجعة مع حدوده. يحتاج تقرير العميل إلى حالة مثبتة وموافقة بشرية.","وثائق الأصل|أدلة السوق|افتراضات مالية|قيود محلية","تحديد القرار والمنطقة|ربط الادعاءات المهمة بالأدلة|اختبار التعارضات والافتراضات|تجهيز أسئلة الخبراء"],
  "international-brand":["استراتيجية العلامة التجارية الدولية والتسويق", "استراتيجية العلامة والتسويق", "ربط أصوات المستهلكين المحليين وأدلة السوق وتموضع العلامة التجارية وتنفيذ التسويق.", "أي سوق يناسب المنتج؟ وكيف نحدد موقعه لدى المستهلك المحلي؟", "توصية للسوق والتموضع مع إظهار فجوات الأدلة والافتراضات.", "المنتج والجمهور|أصوات المستهلكين|المنافسة والثقافة|قنوات التسويق", "فهم المنتج والجمهور|مقارنة الأسواق|تمييز الملاحظة عن الرؤية|صياغة خيارات العلامة والتسويق"],
  travel:["خدمات مهنية للسياح ووكالات السفر", "المسافرون ووكالات السفر", "مساعدة المسافرين على مقارنة الرحلات الجوية والتذاكر وبرامج السفر، ومساعدة الوكالات على تقليل جهد البحث والشراء والتشغيل.", "ما الخيارات المناسبة لاحتياجاتي، وما تكلفتها من وقت ومال؟", "خيارات سفر وخطوات ترتيب واضحة؛ تتطلب الأسعار والتوافر الفعليان مصادر بيانات متصلة.", "احتياجات الرحلة|الرحلات والتذاكر|البرنامج|الأسعار والتوافر", "توضيح الاحتياجات|مقارنة الخيارات والتكلفة الكاملة|تنظيم الشراء والبرنامج"],
  "cross-border":["خدمات تجارة المنتجات عبر الحدود","التوريد والتجارة","تقييم المنتجات والموردين عبر المنصات الصينية ومتطلبات بلد الوجهة.","هل فرصة التوريد هذه مناسبة تجارياً وقابلة للتنفيذ؟","تقدير مشروط ينتظر التحقق من بيانات منصات حقيقية.","أدلة المنصات|ادعاءات الموردين|تكاليف التسليم|متطلبات الوجهة","مقارنة العرض بالأدلة|إظهار المجهول والقيود|تقييم المخاطر التجارية والتنفيذية"],
  "morocco-life":["مساعد شخصي للحياة في المغرب", "الحياة اليومية في المغرب", "مساعدة المقيمين والزوار في معرفة إجراءات الوثائق والسكن والتنقل والخدمات اليومية.", "ما الخطوة العملية المناسبة لظروفي في المغرب؟", "مسار يناسب الحالة ويبين الشكوك ونقاط التحقق الرسمية.", "الظروف الشخصية|الموقع|الشروط الرسمية|الخدمات المحلية", "فهم الوضع|البحث عن المعلومات المناسبة|ترتيب الخطوات ونقاط التحقق"],
  "financial-markets":["نظام اتخاذ القرار في الأوراق المالية", "تحليل الأوراق المالية", "دعم قرارات الأوراق المالية بالاستناد إلى شروطها وأدلة السوق المؤرخة والتفسيرات المتنافسة.", "ما الذي تغير؟ وهل يغير الرأي الحالي في السوق؟", "تحليل سوق قابل للتتبع مع إظهار ما بقي من عدم اليقين.", "شروط الورقة المالية|بيانات السوق|الأحداث وتوقيتها|تفسيرات مختلفة", "ربط الأدلة بالورقة وتاريخ القرار|اختبار التفسيرات|تحديث النتائج المتأثرة"],
  "medical-business":["نظام القرارات التجارية في الصحة","الأعمال الصحية","تصميم نظام محدود النطاق للقرارات التجارية في قطاع الصحة.","أي خيار تجاري تبرره الأدلة المتاحة؟","مرحلة تصميم، وليس أداة للقرارات الطبية أو السريرية.","السياق التجاري|الإطار التنظيمي|أدلة الأطراف المعنية","تحديد الاستخدام والحدود|اختيار المصادر والمراجعين المؤهلين"]
 },
 ary:{
  "banking-frontline":["الخدمة البنكية فالواجهة","قرارات خدمة الزبناء","نعاونو موظفين الواجهة يجاوبو على أسئلة الزبناء بمعلومات خدمة يمكن تتبّعها، ويعرفو وقتاش يحيلو الملف للمتخصص.","شنو نقدر نأكدو لهاد الزبون وشنو خاصو مراجعة من مختص؟","مسار جواب يمكن مراجعته؛ ما كاين حتى ربط بالحسابات ولا بأنظمة المعاملات.","سؤال الزبون|شروط الخدمة|توجيهات البنك|المعلومات الناقصة","نوضحو الطلب والبنك المعني|نتأكدو من معلومات الخدمة|نحددو النواقص والحاجة للإحالة"],
  "real-estate":["العقار","الاستثمار والتطوير","كنشوفو فرصة الاستثمار بالدليل والفرضيات والمخاطر وأسئلة الخبراء.","واش خاصنا نكمّلو فهاد المشروع العقاري؟ وشنو يقدر يبدل القرار؟","ملف استثماري يقدر يتراجع وحدودو باينة. تقرير الزبون خاصو حالة متحقق منها ومراجعة بشرية.","وثائق العقار|دلائل السوق|فرضيات مالية|قيود محلية","نحددو القرار والبلاد|نربطو الادعاءات المهمة بالدليل|نجربو الفرضيات والتعارض|نوجدو أسئلة للخبراء"],
  "international-brand":["استراتيجية الماركة الدولية والتسويق", "استراتيجية الماركة والتسويق", "كنربطو صوت المستهلكين المحليين ودلائل السوق وتموقع الماركة وتنفيذ التسويق.", "فين خاص يدخل هاد المنتوج؟ وكيفاش نتموقعو عند المستهلك المحلي؟", "اقتراح على السوق والتموقع، مع إظهار شنو باقي ناقص وشنو مفترض.", "المنتوج والجمهور|صوت المستهلكين|المنافسة والثقافة|قنوات التسويق", "نفهمو المنتوج والجمهور|نقارنو الأسواق|نفرّقو بين الملاحظة والرؤية|نحضرو خيارات الماركة والتسويق"],
  travel:["خدمات مهنية للسياح ووكالات السفر", "المسافرين ووكالات السفر", "كنعاونو المسافرين يقارنو الطيارات والتيكيات وبرامج الرحلة، ووكالات السفر تنقص مجهود البحث والشراء والتسيير.", "شنو الاختيارات اللي كتناسبني، وشحال كتحتاج من وقت وفلوس؟", "اختيارات وخطوات واضحة؛ الثمن والتوفر الحقيقي خاصهم مصادر بيانات مربوطة.", "احتياجات السفر|الطيارات والتيكيات|برنامج الرحلة|الثمن والتوفر", "نحددو الاحتياجات|نقارنو الاختيارات والتكلفة الكاملة|ننظمو الشراء والبرنامج"],
  "cross-border":["خدمات تجارة المنتوجات بين البلدان","الشراء والتوريد","كنقيّمو المنتوجات والموردين فالمنصات الصينية وشروط بلد الوصول.","واش هاد فرصة التوريد مربحة وممكنة فالتنفيذ؟","تقدير مشروط حتى نتحققو من معطيات المنصات الحقيقية.","دلائل المنصات|كلام الموردين|تكاليف التوصيل|شروط بلد الوصول","نقارنو العرض بالدليل|نبيّنو المجهول والقيود|نقيّمو المخاطر التجارية"],
  "morocco-life":["مساعد شخصي للحياة فالمغرب", "الحياة اليومية فالمغرب", "كنعاونو السكان والزوّار يلقاو معلومات على الوراق والسكن والتنقل وخدمات الحياة اليومية.", "شنو هي الخطوة المناسبة لظروفي فالمغرب؟", "مسار مناسب للحالة، فيه الشكوك والحوايج اللي خاص تتأكد من المصدر الرسمي.", "الوضعية الشخصية|البلاصة|الشروط الرسمية|الخدمات المحلية", "نفهمو الوضعية|نقلبو على المعلومات|نرتبو الخطوات ونقط التأكد"],
  "financial-markets":["نظام القرار فالأوراق المالية", "تحليل الأوراق المالية", "كنعاونو فقرارات الأوراق المالية بشروطها ودلائل السوق المؤرخة والتفسيرات المختلفة.", "شنو تبدل؟ وواش كيبدل النظرة الحالية للسوق؟", "تقدير للسوق يمكن تتبّعو مع توضيح الشك اللي باقي.", "شروط الورقة المالية|معطيات السوق|الأحداث والوقت|تفسيرات مختلفة", "نربطو الدلائل بالورقة ووقت القرار|نجربو التفسيرات|نحدّثو الخلاصات المتأثرة"],
  "medical-business":["نظام القرار التجاري فالصحة","الأعمال الصحية","كنصممو نظام محدد الحدود للقرارات التجارية فالقطاع الصحي.","شنو الاختيار التجاري اللي الدليل المتاح كيسندو؟","باقي فمرحلة التصميم، وماشي أداة للقرارات الطبية.","سياق العمل|القوانين|دلائل الجهات المعنية","نحددو الاستعمال والحدود|نختارو المصادر والخبراء المناسبين"]
 },
 es:{
  "banking-frontline":["Atención bancaria de primera línea","Decisiones de atención al cliente","Ayudar a los equipos bancarios a responder consultas con información de servicio rastreable y criterios claros de derivación.","¿Qué podemos confirmar para este cliente y qué requiere revisión especializada?","Una respuesta revisable; sin conexión con cuentas ni sistemas de transacciones.","Consulta del cliente|Condiciones del servicio|Guías del banco|Datos faltantes","Aclarar la consulta y el banco aplicable|Comprobar información de servicio|Identificar faltantes y derivaciones"],
  "real-estate":["Inmobiliario","Inversión y desarrollo","Examinar oportunidades mediante pruebas, hipótesis, riesgos y revisión experta.","¿Conviene continuar con este inmueble y qué hechos cambiarían la decisión?","Un caso de inversión revisable con límites claros. Un informe para clientes exige un caso verificado y aprobación humana.","Documentos del activo|Datos de mercado|Hipótesis financieras|Restricciones locales","Definir decisión y jurisdicción|Vincular afirmaciones con pruebas|Poner a prueba conflictos e hipótesis|Preparar la revisión experta"],
  "international-brand":["Estrategia internacional de marca y marketing", "Estrategia de marca y marketing", "Conectar las voces de los consumidores locales, las pruebas del mercado, el posicionamiento de marca y la ejecución de marketing.", "¿En qué mercado entrar y cómo posicionar el producto ante consumidores locales?", "Una recomendación de mercado y posicionamiento con lagunas e hipótesis visibles.", "Producto y público|Consumidores locales|Competencia y cultura|Canales de marketing", "Entender producto y público|Comparar mercados|Separar observación e insight|Definir marca y marketing"],
  travel:["Servicios profesionales para turistas y agencias de viajes", "Viajeros y agencias", "Ayudar a viajeros a comparar vuelos, entradas e itinerarios, y a agencias a reducir el esfuerzo de búsqueda, compra y operación.", "¿Qué opciones se ajustan a mis necesidades y cuánto cuestan en tiempo y dinero?", "Opciones y pasos claros; precios y disponibilidad en tiempo real requieren fuentes conectadas.", "Necesidades del viaje|Vuelos y entradas|Itinerario|Precios y disponibilidad", "Aclarar necesidades|Comparar opciones y costes totales|Organizar compras e itinerario"],
  "cross-border":["Servicios de comercio transfronterizo de productos","Abastecimiento y comercio","Evaluar productos y proveedores de plataformas chinas frente a los mercados de destino.","¿Es viable esta oportunidad de abastecimiento?","Juicio condicionado a la validación con datos reales de plataformas.","Datos de plataformas|Afirmaciones del proveedor|Costes de entrega|Requisitos de destino","Comparar oferta y pruebas|Mostrar dudas y límites|Evaluar riesgos comerciales y operativos"],
  "morocco-life":["Asistente personal para vivir en Marruecos", "Vida cotidiana en Marruecos", "Ayudar a residentes y visitantes con información sobre trámites, vivienda, transporte y servicios cotidianos.", "¿Cuál es el siguiente paso práctico en mi situación en Marruecos?", "Una ruta contextualizada con dudas y verificaciones oficiales.", "Situación personal|Ubicación|Requisitos oficiales|Servicios locales", "Entender la situación|Buscar información relevante|Organizar pasos y confirmaciones"],
  "financial-markets":["Sistema de decisión sobre valores financieros", "Análisis de valores", "Apoyar decisiones sobre valores con condiciones del instrumento, pruebas de mercado fechadas y explicaciones alternativas.", "¿Qué ha cambiado y afecta a la visión actual del mercado?", "Una visión trazable con la incertidumbre pendiente.", "Condiciones del valor|Datos de mercado|Eventos y fechas|Explicaciones alternativas", "Vincular pruebas con valor y fecha|Probar interpretaciones|Revisar conclusiones afectadas"],
  "medical-business":["Sistema de decisiones comerciales en salud","Negocios sanitarios","Diseñar un sistema delimitado para decisiones comerciales en salud.","¿Qué opción comercial justifican las pruebas disponibles?","Fase de diseño: no es una herramienta para decisiones clínicas o médicas.","Contexto comercial|Entorno regulatorio|Datos de partes interesadas","Definir uso y límites|Identificar fuentes y revisores adecuados"]
 },
 ja:{
  "banking-frontline":["銀行フロントサービス","顧客対応の判断","追跡可能なサービス情報に基づいて顧客の質問に対応し、専門担当者への引き継ぎが必要な点を明確にします。","この顧客について何を確認でき、何を専門担当者が確認すべきか。","確認可能な対応手順を示します。銀行口座や取引システムには接続していません。","顧客の質問|サービス条件|銀行の案内|不足情報","依頼内容と対象銀行を確認|関連情報を照合|不足点と引き継ぎを特定"],
  "real-estate":["不動産","投資・開発","証拠、前提、リスク、専門家の検証から投資機会を見直します。","この不動産案件を進めるべきか。どんな事実で判断が変わるか。","限界を明示した投資検討資料。顧客向け報告には案件の検証と人による承認が必要です。","物件資料|市場の証拠|財務上の前提|現地の制約","判断事項と地域を定義|重要な主張の根拠を追跡|矛盾と前提を検証|専門家への質問を準備"],
  "international-brand":["国際ブランド戦略・マーケティングシステム", "ブランド戦略とマーケティング", "現地消費者の声、市場の根拠、ブランドの位置づけ、マーケティングの実行を結びます。", "どの市場に参入し、現地消費者にどう位置付けるか。", "証拠の不足と前提を示した市場・ポジショニング案。", "製品と対象者|現地消費者の声|競合と文化|マーケティング経路", "製品と対象者を理解|市場を比較|観察と洞察を区別|ブランドとマーケティングを構築"],
  travel:["観光客・旅行会社向け専門サービスシステム", "旅行者と旅行会社", "旅行者が航空券、入場券、旅程を比較しやすくし、旅行会社の情報収集・調達・運営の負担軽減を目指します。", "自分に合う旅行の選択肢と、必要な時間や費用は何か。", "旅行の選択肢と手配手順を示します。リアルタイムの価格と空き状況にはデータ接続が必要です。", "旅行の希望|航空券と入場券|旅程|価格と空き状況", "旅行者の希望を確認|選択肢と総費用を比較|手配と旅程を整理"],
  "cross-border":["越境商品貿易サービスシステム","調達・貿易","中国のプラットフォームと仕向け先市場に照らして商品と供給者を評価します。","この調達機会は事業と運用の両面で成立するか。","実際のプラットフォーム情報による検証を要する条件付き判断。","プラットフォームの証拠|供給者の主張|配送コスト|仕向け先の要件","提示条件と証拠を比較|不明点と制約を示す|事業と運用のリスクを評価"],
  "morocco-life":["モロッコ生活パーソナルアシスタント", "モロッコの日常生活", "居住者と訪問者が手続き、住居、交通、日常サービスの情報を得られるよう支援します。", "モロッコでの私の状況に合う次の安全な行動は何か。", "不確実性と公的な確認事項を示した個別の道筋。", "個人の状況|場所|公的要件|地域サービス", "状況を理解|関連情報を調べる|手順と確認事項を整理"],
  "financial-markets":["金融証券意思決定システム", "証券分析", "証券の条件、時点を明示した市場の根拠、異なる解釈に基づく判断を支援します。", "何が変わり、現在の市場見通しに影響するか。", "残る不確実性を明示した追跡可能な市場見通し。", "証券の条件|市場データ|出来事と時点|異なる解釈", "証拠を証券と判断時点に対応|解釈を検証|影響を受けた結論を更新"],
  "medical-business":["医療事業判断システム","ヘルスケア事業","医療分野の事業判断に向け、用途を限定したシステムを設計します。","利用可能な証拠はどの事業上の選択を支えるか。","設計段階であり、臨床・医療判断の道具ではありません。","事業の背景|規制環境|関係者の証拠","用途と境界を定義|信頼できる情報源と検証者を選ぶ"]
 },
 th:{
  "banking-frontline":["บริการธนาคารส่วนหน้า","การตัดสินใจด้านบริการลูกค้า","ช่วยทีมบริการธนาคารตอบคำถามลูกค้าด้วยข้อมูลที่ตรวจสอบที่มาได้ และระบุจุดที่ควรส่งต่อให้ผู้เชี่ยวชาญ","ข้อมูลใดที่ยืนยันให้ลูกค้าได้ และเรื่องใดต้องให้ผู้เชี่ยวชาญตรวจสอบ","แนวทางตอบกลับที่ตรวจทานได้ ยังไม่เชื่อมต่อบัญชีหรือระบบธุรกรรมธนาคาร","คำถามลูกค้า|เงื่อนไขบริการ|คำแนะนำของธนาคาร|ข้อมูลที่ขาด","ชี้แจงคำขอและธนาคารที่เกี่ยวข้อง|ตรวจสอบข้อมูลบริการ|ระบุข้อมูลที่ขาดและการส่งต่อ"],
  "real-estate":["อสังหาริมทรัพย์","การลงทุนและพัฒนา","พิจารณาโอกาสลงทุนจากหลักฐาน สมมติฐาน ความเสี่ยง และการทักท้วงของผู้เชี่ยวชาญ","ควรเดินหน้าโครงการนี้หรือไม่ และข้อเท็จจริงใดจะเปลี่ยนคำตัดสิน","กรณีลงทุนที่ตรวจทานได้และระบุข้อจำกัด รายงานสำหรับลูกค้ายังต้องผ่านกรณีจริงและการลงนามของผู้เชี่ยวชาญ","เอกสารทรัพย์สิน|หลักฐานตลาด|สมมติฐานการเงิน|ข้อจำกัดท้องถิ่น","กำหนดการตัดสินใจและพื้นที่|โยงข้ออ้างสำคัญกับหลักฐาน|ทดสอบข้อขัดแย้งและสมมติฐาน|เตรียมคำถามให้ผู้เชี่ยวชาญ"],
  "international-brand":["ระบบกลยุทธ์แบรนด์ระหว่างประเทศและการตลาด", "กลยุทธ์แบรนด์และการตลาด", "เชื่อมเสียงผู้บริโภคท้องถิ่น หลักฐานตลาด การวางตำแหน่งแบรนด์ และการดำเนินงานการตลาด", "สินค้าควรเข้าสู่ตลาดใด และควรวางตำแหน่งอย่างไรต่อผู้บริโภคท้องถิ่น", "คำแนะนำด้านตลาดและตำแหน่งแบรนด์ที่แสดงช่องว่างข้อมูลและสมมติฐาน", "สินค้าและกลุ่มเป้าหมาย|เสียงผู้บริโภคท้องถิ่น|คู่แข่งและวัฒนธรรม|ช่องทางการตลาด", "ทำความเข้าใจสินค้าและกลุ่มเป้าหมาย|เปรียบเทียบตลาด|แยกข้อสังเกตจากข้อค้นพบ|วางแนวทางแบรนด์และการตลาด"],
  travel:["ระบบบริการวิชาชีพสำหรับนักท่องเที่ยวและบริษัทท่องเที่ยว", "นักท่องเที่ยวและบริษัททัวร์", "ช่วยนักท่องเที่ยวเปรียบเทียบตั๋วเครื่องบิน บัตรเข้าชม และแผนเดินทาง พร้อมช่วยบริษัททัวร์ลดภาระการหาข้อมูล จัดซื้อ และดำเนินงาน", "ตัวเลือกใดเหมาะกับความต้องการของฉัน และใช้เวลาและเงินเท่าไร", "แสดงตัวเลือกและขั้นตอนการจัดการเดินทาง โดยราคาและจำนวนที่ว่างแบบปัจจุบันต้องเชื่อมต่อแหล่งข้อมูล", "ความต้องการเดินทาง|เที่ยวบินและบัตรเข้าชม|แผนเดินทาง|ราคาและจำนวนที่ว่าง", "ระบุความต้องการ|เปรียบเทียบทางเลือกและต้นทุนรวม|จัดลำดับการซื้อและแผนเดินทาง"],
  "cross-border":["ระบบบริการค้าสินค้าข้ามพรมแดน","จัดหาและการค้า","ประเมินสินค้าและผู้ขายบนแพลตฟอร์มจีนเทียบกับเงื่อนไขตลาดปลายทาง","โอกาสจัดหานี้คุ้มค่าและทำได้จริงหรือไม่","ข้อวินิจฉัยแบบมีเงื่อนไข รอการตรวจสอบข้อมูลแพลตฟอร์มจริง","หลักฐานแพลตฟอร์ม|คำกล่าวอ้างของผู้ขาย|ต้นทุนส่งมอบ|ข้อกำหนดปลายทาง","เปรียบเทียบข้อเสนอและหลักฐาน|แสดงสิ่งที่ยังไม่รู้|ประเมินความเสี่ยงธุรกิจและปฏิบัติการ"],
  "morocco-life":["ผู้ช่วยส่วนตัวด้านการใช้ชีวิตในโมร็อกโก", "ชีวิตประจำวันในโมร็อกโก", "ช่วยผู้อยู่อาศัยและผู้มาเยือนหาข้อมูลเรื่องเอกสาร ที่พัก การเดินทาง และบริการในชีวิตประจำวัน", "ขั้นต่อไปที่เหมาะกับสถานการณ์ของฉันในโมร็อกโกคืออะไร", "เส้นทางการดำเนินการตามบริบท พร้อมจุดไม่แน่นอนและสิ่งที่ต้องยืนยันกับหน่วยงาน", "สถานการณ์ส่วนตัว|ที่ตั้ง|ข้อกำหนดทางการ|บริการท้องถิ่น", "เข้าใจสถานการณ์|ค้นหาข้อมูลที่เกี่ยวข้อง|จัดลำดับขั้นตอนและสิ่งที่ต้องยืนยัน"],
  "financial-markets":["ระบบตัดสินใจด้านหลักทรัพย์การเงิน", "การวิเคราะห์หลักทรัพย์", "ช่วยพิจารณาหลักทรัพย์จากเงื่อนไขตราสาร หลักฐานตลาดตามเวลา และคำอธิบายที่แตกต่างกัน", "มีอะไรเปลี่ยน และส่งผลต่อมุมมองตลาดปัจจุบันหรือไม่", "มุมมองตลาดที่ตรวจสอบย้อนกลับได้พร้อมความไม่แน่นอนที่เหลือ", "เงื่อนไขหลักทรัพย์|ข้อมูลตลาด|เหตุการณ์และเวลา|คำอธิบายที่ต่างกัน", "โยงหลักฐานกับหลักทรัพย์และเวลาตัดสินใจ|ทดสอบคำอธิบาย|ปรับข้อสรุปที่ได้รับผล"],
  "medical-business":["ระบบตัดสินใจทางธุรกิจการแพทย์","ธุรกิจสุขภาพ","ออกแบบระบบขอบเขตชัดเจนสำหรับการตัดสินใจทางธุรกิจด้านสุขภาพ","หลักฐานที่มีสนับสนุนทางเลือกธุรกิจใด","อยู่ในขั้นออกแบบ ไม่ใช้ตัดสินใจทางคลินิกหรือการรักษา","บริบทธุรกิจ|กฎระเบียบ|ข้อมูลผู้เกี่ยวข้อง","กำหนดการใช้งานและขอบเขต|เลือกแหล่งและผู้ตรวจที่เหมาะสม"]
 }
};

export function translatedProducts(locale:Locale):Product[]{
  if(locale==="en")return products;
  return products.map(p=>{
    const entry=localized[locale][p.slug];
    if(!entry)throw new Error(`Missing product translation: ${locale}/${p.slug}`);
    const [title,domain,summary,question,outcome,signals,work]=entry;
    return {...p,title,domain,status:status[locale][p.status],summary,question,signals:signals.split("|"),work:work.split("|"),outcome};
  });
}
export function translatedProduct(locale:Locale,slug:string){return translatedProducts(locale).find(p=>p.slug===slug);}
export function translatedStatus(locale:Locale,value:string){return status[locale][value]??value;}
